apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: projeto-api-conversao
          image: liip3lim4/api-conversao:v1
          ports:
            - containerPort: 8080
